import type { Metadata } from 'next'
import { Bebas_Neue, DM_Sans, Inter, Raleway } from 'next/font/google'
import '../globals.css'
import WorkspaceLayout from './workspace-layout';
import AppNavBar from './nav';
import SideBar from './sidebar';

const inter = Inter({ subsets: ['latin'], weight: ['200', '400'], variable:'--font-inter'})

const dmSans = DM_Sans({
  subsets: ['latin'],
  weight: ['200', '400', '500' , '600', '700', '800','900', '1000'],
  variable:'--font-dm-sans'
});

const bebasNeue = Bebas_Neue({
  subsets: ['latin'],
  weight: ['400'],
  variable: '--font-bebas-neue',
});

const raleway = Raleway({
  subsets: ['latin'],
  weight: ['200','400'],
  variable: '--font-raleway',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function AppLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <title>Dashboard</title>  
      <body 
        className={`${dmSans.variable} ${bebasNeue.variable} ${raleway.variable} ${inter.variable}`}>
            <AppNavBar/>
            <WorkspaceLayout>
                {children}
            </WorkspaceLayout>
        </body>
    </html>
  )
}
